/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Code.Conversor;

/**
 *
 * @author alejandro
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        jLabel1.setText("Metros");
        jLabel2.setText("Millas");
        jTextField1.setText("0");
        jTextField2.setText("0");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxMedidas = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxMedidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Km/Millas", "L/Galones", "Dólares/Euros", "Metros/Pies" }));
        jComboBoxMedidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMedidasItemStateChanged(evt);
            }
        });
        jComboBoxMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMedidasActionPerformed(evt);
            }
        });

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Metros");

        jLabel2.setText("Millas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jComboBoxMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jComboBoxMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMedidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMedidasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        switch((String)jComboBoxMedidas.getSelectedItem()){
            case"Km/Millas":
                jTextField2.setText(Double.toString(Conversor.kmAMillas(Integer.parseInt(jTextField1.getText()))));
                break;
            
            case"L/Galones":
                jTextField2.setText(Double.toString(Conversor.lAGalones(Integer.parseInt(jTextField1.getText()))));
                break;
                
            case"Dólares/Euros":
                jTextField2.setText(Double.toString(Conversor.dolaresAEuros(Integer.parseInt(jTextField1.getText()))));
                break;
                
            case"Metros/Pies":
                jTextField2.setText(Double.toString(Conversor.metrosAPies(Integer.parseInt(jTextField1.getText()))));
                break;
                
                
        }
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBoxMedidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMedidasItemStateChanged
        // TODO add your handling code here:
        cambiaLabels((String)jComboBoxMedidas.getSelectedItem());
   
    }//GEN-LAST:event_jComboBoxMedidasItemStateChanged

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        switch((String)jComboBoxMedidas.getSelectedItem()){
            case"Km/Millas":
                jTextField1.setText(Double.toString(Conversor.millasAKm(Integer.parseInt(jTextField2.getText()))));
                break;
            
            case"L/Galones":
                jTextField1.setText(Double.toString(Conversor.galonesAL(Integer.parseInt(jTextField2.getText()))));
                break;
                
            case"Dólares/Euros":
                jTextField1.setText(Double.toString(Conversor.eurosADolares(Integer.parseInt(jTextField2.getText()))));
                break;
                
            case"Metros/Pies":
                jTextField1.setText(Double.toString(Conversor.piesAMetros(Integer.parseInt(jTextField2.getText()))));
                break;
                
                
        }
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    public void cambiaLabels(String modo){
        switch(modo){
            case"Km/Millas":
                reiniciaTextFields();
                jLabel1.setText("Km");
                jLabel2.setText("Millas");
                break;
            
            case"L/Galones":
                reiniciaTextFields();
                jLabel1.setText("Litros");
                jLabel2.setText("Galones");
                break;
                
            case"Dólares/Euros":
                reiniciaTextFields();
                jLabel1.setText("Dólares");
                jLabel2.setText("Euros");
                break;
                
            case"Metros/Pies":
                reiniciaTextFields();
                jLabel1.setText("Metros");
                jLabel2.setText("Pies");
                break;
                
                
        }
    }
    public void reiniciaTextFields(){
        jTextField1.setText("0");
        jTextField2.setText("0");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxMedidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
